### ISSUE TITLE
Add support for API version 19

### ISSUE THREAD

**Issue by curantes** [stevemeier/cefs#1]
The errata script is not working for Spacewalk version 2.6.

The error below comes when I run it after upgrading to Spacewalk 2.6

`INFO: Server is running API version 19`
`ERROR: API version 19 is not supported. Try upgrading this script.`

Please add support for API version 19.

**Comment by stevemeier** [comment]
This should be fixed with the recent commits.
Please not that the tarball on the homepage has not been updated yet so please download errata-import.pl from GitHub to test. Thanks!
