### ISSUE TITLE
CDN XML Formatting

### ISSUE THREAD

**Issue by mrwilson** [stevemeier/cefs#10]
Hi,

We've noticed that the CDN-served errata.xml is being reformatted which is breaking XML parsing in downstream applications (see https://github.com/wied03/centos-package-cron/issues/24)

In the "raw" (still on [GitHub](https://raw.githubusercontent.com/stevemeier/cefs/master/errata.latest.xml)) an entry is formatted as

```xml
<CEBA-2018--0330 description="Not available" from="centos-announce@centos.org" issue_date="2018-04-26 17:41:10" notes="Not available" product="CentOS Linux" references="https://access.redhat.com/errata/RHBA-2018:0330 https://lists.centos.org/pipermail/centos-cr-announce/2018-April/004796.html" release="1" solution="Not available" synopsis="CentOS fio BugFix Update" topic="Not available" type="Bug Fix Advisory">
    <os_arch>x86_64</os_arch>
    <os_release>7</os_release>
    <packages>fio-3.1-2.el7.x86_64.rpm</packages>
  </CEBA-2018--0330>
```

In the version served from the CDN

```xml
<CEBA-2018--0330 description="Not available" from="centos-announce@centos.org" issue_date="2018-04-26 17:41:10" notes="Not available" os_arch="x86_64" os_release="7" packages="fio-3.1-2.el7.x86_64.rpm" product="CentOS Linux" references="https://access.redhat.com/errata/RHBA-2018:0330 https://lists.centos.org/pipermail/centos-cr-announce/2018-April/004796.html" release="1" solution="Not available" synopsis="CentOS fio BugFix Update" topic="Not available" type="Bug Fix Advisory"/>
```

What we're observing is that single-instance properties e.g. `os_release` are pulled into the root node as properties rather than child XML elements.

Thanks,

@mrwilson and @tsetsova

**Comment by stevemeier** [comment]
Oh, the wonders of XML.

I have updated the script that minifies the file delivered through the CDN and pushed out a new version, purging the old one. This should now be fixed.

Please let me know if that fixes your issue.

**Comment by mrwilson** [comment]
Thanks for the speedy response! It's certainly fixed the centos-package-cron parsing. :)
