### ISSUE TITLE
[question] Planned support for Amazon Linux erratas

### ISSUE THREAD

**Issue by angystardust** [stevemeier/cefs#11]
Hi @stevemeier Just a question for you: do you plan support for importing Amazon ALAS (
Amazon Linux Security Center) erratas into Spacewalk?
https://alas.aws.amazon.com/

**Comment by angystardust** [comment]
The idea is to write a parser for the RSS feed and convert it to an xml compatible for Spacewalk:
https://alas.aws.amazon.com/alas.rss

**Comment by stevemeier** [comment]
If you want Amazon Errata in your Spacewalk server, simply sync their amzn-updates repository and the errata will be included, just like with EPEL.

The URL for spacewalk-repo-sync would be:
http://packages.eu-west-1.amazonaws.com/2018.03/updates/d2402a38af42/x86_64/

Replace eu-west-1 with your closest AWS region.
