### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by nachfuellbar** [stevemeier/cefs#12]
Hello,

i don't know why this error isn't handled (it seems like there is exception handling for this)
I've got an error after authenticating with wrong password. I'm pretty sure i should get an return value of 3 from your script but i got 255.

`Fault returned from XML RPC Server, fault code 2950: redstone.xmlrpc.XmlRpcFault: Either the password or username is incorrect.`

Spacewalk version is 2.5.1

Thanks in advance

**Comment by stevemeier** [comment]
Can you provides steps to reproduce this?
Looking at the code I don't see how this could happen.

**Comment by nachfuellbar** [comment]
It took me some time to recall what i did ;)
It was as simple as this; only password was wrong:

export SPACEWALK_USER="XXXX"
export SPACEWALK_PASS="XXXXX"
/usr/sbin/errata-import.pl --server localhost --errata errata.latest.xml --rhsa-oval com.redhat.rhsa-all.xml --publish

**Comment by nachfuellbar** [comment]
Just thought about how the OS would impact this and it seems like i forgot to mention:
Tested on CentOS 6.10

**Comment by kathirvel1980** [comment]
Fault returned from XML RPC Server, fault code 2950: redstone.xmlrpc.XmlRpcFault: Either the password or username is incorrect

**Comment by stevemeier** [comment]
@kathirvel1980 Can you confirm that you can log into the WebUI with the same credentials you have provided to the script?

**Comment by GSiemons** [comment]
/usr/local/centos/errata-import.pl --server 'lvt-suma-t01.ads.vhv.de' --debug --errata /usr/local/centos/errata.latest.xml -include-channels=centos7-x86_64-updates,centos7-x86_64,centos7-x86_64-extras --publish --rhsa-oval /usr/local/centos/com.redhat.rhsa-RHEL7.xml
DEBUG: Called as /usr/local/centos/errata-import.pl --server lvt-suma-t01.ads.vhv.de --debug --errata /usr/local/centos/errata.latest.xml -include-channels=centos7-x86_64-updates,centos7-x86_64,centos7-x86_64-extras --publish --rhsa-oval /usr/local/centos/com.redhat.rhsa-RHEL7.xml
DEBUG: Version is 20201023
INFO: Server is running API version 24
INFO: API version 24 is supported
INFO: Authentication successful
DEBUG: User is assigned these roles: activation_key_admin satellite_admin org_admin config_admin image_admin cluster_admin channel_admin system_group_admin
INFO: User has administrator access to this server
INFO: Loading errata XML
DEBUG: XML loaded successfully
INFO: Loading Red Hat OVAL XML
DEBUG: Red Hat OVAL XML loaded successfully
INFO: Getting server inventory
DEBUG: --include-channels set: centos7-x86_64-updates,centos7-x86_64,centos7-x86_64-extras
INFO: Channel SLES12-SP4-Pool for x86_64 (sles12-sp4-pool-x86_64) is NOT included
INFO: Channel SLE-Module-Legacy12-Pool for x86_64 SP4 (sle-module-legacy12-pool-x86_64-sp4) is NOT included
DEBUG: Found existing errata for SUSE-12-SP4-2020-1859
.
.
.
DEBUG: Found existing errata for CL-SUSE-15-SP2-2020-1816
DEBUG: Found existing errata for CL-SUSE-15-SP2-2020-1769
DEBUG: Found existing errata for CL-SUSE-15-SP2-2020-1677
INFO: Channel sumprx-tst-SLE-Module-Server-Applications15-SP2-Updates for x86_64 (sumprx-tst-sle-module-server-applications15-sp2-updates-x86_64) is NOT included
INFO: Channel epel-8 (epel-8) is NOT included
INFO: Channel SLES12-SP5-Pool for x86_64 (sles12-sp5-pool-x86_64) is NOT included
DEBUG: Processing CEBA-2018:0748
DEBUG: Package: elinks-0.12-0.37.pre6.el7.x86_64.rpm not found
DEBUG: Package: js-1.8.5-20.el7.i686.rpm -> 204595 -> centos7-x86_64
DEBUG: Package: js-1.8.5-20.el7.x86_64.rpm -> 204630 -> centos7-x86_64
DEBUG: Package: js-devel-1.8.5-20.el7.i686.rpm -> 204639 -> centos7-x86_64
DEBUG: Package: js-devel-1.8.5-20.el7.x86_64.rpm -> 204608 -> centos7-x86_64
DEBUG: find_packages advisory: CEBA-2018--0748
DEBUG: find_packages packages: 204639,204608,204595,204630
DEBUG: find_packages channels: centos7-x86_64
INFO: Creating errata for CEBA-2018:0748 (CentOS elinks BugFix Update) (4 of 5)
Fault returned from XML RPC Server, fault code -23: redstone.xmlrpc.XmlRpcFault: You do not have permissions to perform this action.

So the commmand quits with the fault Code -23, The  export SPACEWALK_USER='XXX' and  export SPACEWALK_PASS='XXX' is valid and i can already do a Web Gui Login with these credentials, 

Do you have a hint what´s going wrong here ? Using SUMA 4.1.2 on PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"

Kind Regards

GSi

**Comment by GSiemons** [comment]
additional Info : ( Permission granted through org/channel admin status, or the channel is globally subscribable)  for the used User

**Comment by stevemeier** [comment]
The way I read the SuSE Manager changelog, the CentOS channels are "special" and can therefore not be modified directly.
You need to clone them and apply the errata to the cloned channel, I think.

See https://www.suse.com/releasenotes/x86_64/SUSE-MANAGER/4.1/#_third_party_errata_information_for_vendor_channels

**Comment by GSiemons** [comment]
Thank You very much Steve, we will try this and clone the CentOS Channels and apply than the errata

**Comment by GSiemons** [comment]
He Steve, until i made this in the right way like you described it to me, IT´s Working the Right Way 8-)
INFO: Errata created: 85
INFO: Errata updated: 0
DEBUG: Logging out.
