### ISSUE TITLE
Errata is not imported if package is newer than package mentioned in errata file

### ISSUE THREAD

**Issue by Erkak** [stevemeier/cefs#13]
Hello,

If package version in channel is newer than package that is mentioned in errata file, errata will not be imported in spacewalk.
For example, CESA-2017--2832 based on errata file can be fixed by the following packages:
<packages>nss-3.28.4-12.el7_4.i686.rpm</packages>
    <packages>nss-3.28.4-12.el7_4.src.rpm</packages>
    <packages>nss-3.28.4-12.el7_4.x86_64.rpm</packages>
    <packages>nss-3.28.4-4.el6_9.i686.rpm</packages>
    <packages>nss-3.28.4-4.el6_9.src.rpm</packages>
    <packages>nss-3.28.4-4.el6_9.x86_64.rpm</packages>
    <packages>nss-devel-3.28.4-12.el7_4.i686.rpm</packages>
    <packages>nss-devel-3.28.4-12.el7_4.x86_64.rpm</packages>
    <packages>nss-devel-3.28.4-4.el6_9.i686.rpm</packages>
    <packages>nss-devel-3.28.4-4.el6_9.x86_64.rpm</packages>
    <packages>nss-pkcs11-devel-3.28.4-12.el7_4.i686.rpm</packages>
    <packages>nss-pkcs11-devel-3.28.4-12.el7_4.x86_64.rpm</packages>
    <packages>nss-pkcs11-devel-3.28.4-4.el6_9.i686.rpm</packages>
    <packages>nss-pkcs11-devel-3.28.4-4.el6_9.x86_64.rpm</packages>
    <packages>nss-sysinit-3.28.4-12.el7_4.x86_64.rpm</packages>
    <packages>nss-sysinit-3.28.4-4.el6_9.i686.rpm</packages>
    <packages>nss-sysinit-3.28.4-4.el6_9.x86_64.rpm</packages>
    <packages>nss-tools-3.28.4-12.el7_4.x86_64.rpm</packages>
    <packages>nss-tools-3.28.4-4.el6_9.i686.rpm</packages>
    <packages>nss-tools-3.28.4-4.el6_9.x86_64.rpm</packages>

But my channel for CentOS 7 contains the following packages:
nss-3.28.4-15.el7_4.i686
nss-3.28.4-15.el7_4.x86_64 
nss-devel-3.28.4-15.el7_4.i686
nss-devel-3.28.4-15.el7_4.x86_64 
nss-pkcs11-devel-3.28.4-15.el7_4.i686
nss-pkcs11-devel-3.28.4-15.el7_4.x86_64
nss-sysinit-3.28.4-15.el7_4.x86_64
nss-tools-3.28.4-15.el7_4.x86_64

So, script "errata-import.pl" doens't import errata for my channel because it can't find appropriate package. 
I think this is not correct, because package nss-3.28.4-15.el7_4.x86_64 is newer than nss-3.28.4-12.el7_4.x86_64 and can be used for fixing that vulnerability.

**Comment by stevemeier** [comment]
This is not a bug.

Errata apply to one version of a package and one version only.

To use your example:
CESA-2017:2832 is fixed by nss-3.28.4-**12**.el7_4.x86_64.rpm (and others)
CEBA-2017:2942 is fixed by nss-3.28.4-**15**.el7_4.x86_64.rpm (and others)

When you install the newer package the older Errata will also be marked as resolved.

**Comment by Erkak** [comment]
Thank you for reply.
We use spacewalk for system management.
The matter is that CESA is related to security fixes (marked as "Critical" in Spacewalk), and CEBA is related to Bug Fixes (marked as "Not critical" in Spacewalk). So, if we want to apply just Critical updates to the system via Spacewalk, CESA-2017:2832 in such case will not be resolved.

Best regards

**Comment by stevemeier** [comment]
If you install only CESA errata (security) only, then other bugs (CEBA) may persist.
The theory of installing only security updates sounds nice but has its shortcomings.

**Comment by Erkak** [comment]
That's a pity!
Anyway, thank you very much for explanation.
I've marked issue as resolved.
