### ISSUE TITLE
416: Requested Range Not Satisfiable

### ISSUE THREAD

**Issue by nryn** [stevemeier/cefs#14]
Hi,

When attempting to access errata from https://cefs.steve-meier.de/errata.latest.xml, we're getting a 416 response from nginx after being redirected to https://cefs.b-cdn.net/errata.latest.xml

In the mean time we're relying on the raw errata xml hosted here on github.

Thanks,

@nryn and @tsetsova

**Comment by stevemeier** [comment]
This issue was caused by a failed upload to the CDN.
It should now be resolved.
