### ISSUE TITLE
Support for API version 22

### ISSUE THREAD

**Issue by andymcmullen** [stevemeier/cefs#15]
Hi,

I have a fresh install of Spacewalk synced to a Centos7 mirror.  when I tried running your errata import script, I got an error message that the script does not support API version 22.  Is support for the new API planned?

Thanks,

**Comment by stevemeier** [comment]
Can you run the script with the `--ignore-api-version` parameter?

Usually new API versions are fine but they are not enabled by default.

**Comment by stevemeier** [comment]
API version 22 is now supported with the latest commit:
https://github.com/stevemeier/cefs/commit/4c26f5e7a9051303e807433b8f3cb7e09546ac1e
