### ISSUE TITLE
Fault returned from XML RPC Server

### ISSUE THREAD

**Issue by leomatosouza** [stevemeier/cefs#17]
Hello, 

I am having problems importing errata when it arrives in the part of security errata:

Fault returned from XML RPC Server, fault code -1: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: Specified severity is not correct!

Spacewalk versions 2.8 and 2.9

Thanks

**Comment by stevemeier** [comment]
Please run the script with `--debug` and provide the full output.
Given just this error message, I can not do any debugging.

**Comment by leomatosouza** [comment]
Hi,

Follows the execution of the script with --debug 

[centos6.9_x86_64_base.log](https://github.com/stevemeier/cefs/files/3025586/centos6.9_x86_64_base.log)

Thanks

**Comment by stevemeier** [comment]
That is very odd. That is a valid severity according to the documentation and it worked for me:

https://spacewalkproject.github.io/documentation/api/2.8/handlers/ErrataHandler.html#setDetails
https://spacewalkproject.github.io/documentation/api/2.9/handlers/ErrataHandler.html#setDetails

I assume this is an issue with your Spacewalk installation.
Would you mind sending it to the Spacewalk Mailing List?
https://www.redhat.com/mailman/listinfo/spacewalk-list

**Comment by leomatosouza** [comment]
Hello,

It is really a problem with my installation. I performed a new installation and it worked for me.

I will sending it to the Spacewalk Mailing List.

Thank you very much.
