### ISSUE TITLE
errata-import.pl no longer supported spacewalk 2.7

### ISSUE THREAD

**Issue by xxdrew21xx** [stevemeier/cefs#2]
Hi ,
I'm been using the script on spacewalk v2.6 and its doing great but after i upgraded to spacewalk v2.7 its no longer working and receiving error message that api not supported. Is it possible to have an updated script that support spacewalk v2.7 Thanks

./errata-import.pl --server spacewalk.internal --errata errata.latest.xml  --rhsa-oval com.redhat.rhsa-all.xml  --include-channels centos5x-base-x86_64 --publish
INFO: Server is running API version 20
ERROR: API version 20 is not supported. Try upgrading this script.

**Comment by stevemeier** [comment]
I have updated the script to accept API version 20 now.
Updated script is available here on GitHub as well as on the website.

Thanks for reporting this.

**Comment by xxdrew21xx** [comment]
Thanks for the quick response.   :)
