### ISSUE TITLE
Not included channels losing packages

### ISSUE THREAD

**Issue by jonmert** [stevemeier/cefs#21]
Hi,

I set up a new spacewalk server.

5 channels
- ch1 --> repo1
- ch2 --> repo1
- ch3  --> repo2
- ch4 --> repo2
- ch_daily --> repo1&+ repo2

by running `SPACEWALK_PASS=<SECURE> SPACEWALK_USER=<USER> /opt/tools/errata_import.pl --server localhost --errata errata.latest.xml --include-channels ch_daily --rhsa-oval=/tmp/com.redhat.rhsa-all.xml --publish`
the erata are created, but ch1-4 are loosing some packages (maybe the ones with  newly created erata).

Please let me know, if you need more information.

Merry christmas.

**Comment by jonmert** [comment]
This is the debug. Log. Maybee an configuration issue on my site? 

> DEBUG: Previous channel membership for 4293: ch_daily
DEBUG: Current channel membership for 4293: ch_daily,ch1,ch2
DEBUG: Package 4293 has been auto-pushed to ch1,ch2
DEBUG: Removing package 4293 from ch1
DEBUG: Removing package 4293 from ch2

**Comment by stevemeier** [comment]
Hello,

while the excerpt from the debug log looks OK, I think it shouldn't have published to those channels in the first place since you specified --include-channels.

Could you please post the full debug log so that I can also have a look at the initialisation phase?
Thanks!

**Comment by jonmert** [comment]
Hi @stevemeier 

please see attached log. [debug.log](https://github.com/stevemeier/cefs/files/4016037/debug.log)

Before erata import package count:
centos7-parent	0
Sub-Channel ch_daily	11107
Sub-Channel ch1	10097
Sub-Channel ch2	10097
Sub-Channel ch3	1010
Sub-Channel ch4	1010


After erata import package count:
Sub-Channel ch_daily	11107
Sub-Channel ch1	7424
Sub-Channel ch2	7424
Sub-Channel ch3	38
Sub-Channel ch4	38

**Comment by stevemeier** [comment]
[errata-import.pl.txt](https://github.com/stevemeier/cefs/files/4016733/errata-import.pl.txt)

Hi @jonmert 

I think I understand what is going on here. While --include-channels makes sure that only the certain channels are scanned, the removal part does not check wether the channel is in scope and may therefore go "out of bounds".

I have added code to check that in the attached version. Could you give that a try and post your results here? Thanks!

**Comment by jonmert** [comment]
Hi @stevemeier 

works as expected. Now only the included channel is touched. Thank you very much.
