### ISSUE TITLE
License is not specified

### ISSUE THREAD

**Issue by moio** [stevemeier/cefs#22]
:wave: @stevemeier!

Context: I am a SUSE employee and an Uyuni contributor, and I am about to prepare a pull request to solve an incompatibility with the latest Uyuni release (one XMLRPC API has changed slightly - https://github.com/uyuni-project/uyuni/issues/2386, https://github.com/uyuni-project/uyuni/pull/2296).

Problem: in order for me to contribute to cefs va license for the project should be specified. I can do that via PR myself if that works best for you, just let me know what license is best to you.

Any OSI one is perfectly acceptable, I personally have a slight preference for MIT if unsure.

https://choosealicense.com/

**Comment by stevemeier** [comment]
I have added a note on licenses to the README.md
Is this sufficient for you?

**Comment by moio** [comment]
Yes, thank you!
