### ISSUE TITLE
[Question] is it normal that CentOS 8 does not have errata since May?

### ISSUE THREAD

**Issue by moio** [stevemeier/cefs#28]
What I see is:

$ wget https://cefs.steve-meier.de/errata.latest.xml
$ grep "<os_release>8</os_release>" < ./errata.latest.xml -B 5 | grep -Eo 'issue_date="[^"]*"' | sort  | tail
issue_date="2020-04-30 00:00:00"
issue_date="2020-04-30 00:00:00"
issue_date="2020-04-30 00:00:00"
issue_date="2020-05-05 00:00:00"
issue_date="2020-05-06 00:00:00"
issue_date="2020-05-11 00:00:00"
issue_date="2020-05-12 00:00:00"
issue_date="2020-05-12 00:00:00"
issue_date="2020-05-13 00:00:00"
issue_date="2020-05-20 00:00:00"

(no errata for CentOS 8 having issue date after May in errata.latest.xml)

This seems to contradict the fact that some advisories were published in June and July, eg. https://access.redhat.com/errata/RHSA-2020:2828 dated 2020-07-06.

It is not clear to me whether this is expected or not, being no CentOS expert myself.

Can you maybe enlighten me @stevemeier?

:innocent:

**Comment by stevemeier** [comment]
% curl -sL https://cefs.steve-meier.de/errata.latest.xml | grep -B5 "<os_release>8</os_release>" | grep -Eo 'issue_date="[^"]*"' | sort | tail
issue_date="2020-05-06 00:00:00"
issue_date="2020-05-11 00:00:00"
issue_date="2020-05-12 00:00:00"
issue_date="2020-05-12 00:00:00"
issue_date="2020-05-13 00:00:00"
issue_date="2020-05-20 00:00:00"
issue_date="2020-05-28 00:00:00"
issue_date="2020-07-06 00:00:00"
issue_date="2020-07-07 00:00:00"
issue_date="2020-07-07 00:00:00"

Maybe wget has duped you by writing to errata.latest.xml.1 and you grep'ed through an old version?

**Comment by moio** [comment]
Not really it seems:

```
silvio@lenovo:~/Downloads> ls -lah errata.latest.xml
-rw-r--r-- 1 silvio users 1.4M Jul  9 09:46 errata.latest.xml
silvio@lenovo:~/Downloads> cat errata.latest.xml | grep -B5 "<os_release>8</os_release>" | grep -Eo 'issue_date="[^"]*"' | sort | tail
issue_date="2020-04-30 00:00:00"
issue_date="2020-04-30 00:00:00"
issue_date="2020-04-30 00:00:00"
issue_date="2020-05-05 00:00:00"
issue_date="2020-05-06 00:00:00"
issue_date="2020-05-11 00:00:00"
issue_date="2020-05-12 00:00:00"
issue_date="2020-05-12 00:00:00"
issue_date="2020-05-13 00:00:00"
issue_date="2020-05-20 00:00:00"
```

(notice the file creation date, Jul 9, yesterday morning)

I do see the three extra patches in July **right now** as you reported:

```
# file removed and redownloaded...

silvio@lenovo:~/Downloads> ls -lah errata.latest.xml
-rw-r--r-- 1 silvio users 1.4M Jul 10 09:37 errata.latest.xml
silvio@lenovo:~/Downloads> cat errata.latest.xml | grep -B5 "<os_release>8</os_release>" | grep -Eo 'issue_date="[^"]*"' | sort | tail
issue_date="2020-05-06 00:00:00"
issue_date="2020-05-11 00:00:00"
issue_date="2020-05-12 00:00:00"
issue_date="2020-05-12 00:00:00"
issue_date="2020-05-13 00:00:00"
issue_date="2020-05-20 00:00:00"
issue_date="2020-05-28 00:00:00"
issue_date="2020-07-06 00:00:00"
issue_date="2020-07-07 00:00:00"
issue_date="2020-07-07 00:00:00"
```

(notice the file creation date, Jul 10, today)

 Still, nothing at all for the whole month of June, is that expected?

**Comment by stevemeier** [comment]
The `issue_date` is a bit of a red herring for CentOS 8.

For CentOS 6 and 7, it is set to date of the first announcement on the mailing-list.
For CentOS 8, as there are no such announcements, it is currently identical to the Red Hat Erratum date.

Of course, the CentOS 8 RPMs are released with some delay, so there were updates in June.
Ideally, the issue date would be set to the date the file(s) showed up on a CentOS mirror for the first time but this is something on the long-term roadmap.
