### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by mithilasliit** [stevemeier/cefs#3]
Hi,
I'm try to sync centos errata with space walk 2.7
after executing ./ya-errata-import.pl with all parameters it return "404 Not Found" in below code snip i try with https but ti was also fail with (LWP::Protocol::https not installed) but this component also installed in the server , please help
$client = new Frontier::Client(url => "http://$opt_server/rpc/api");

**Comment by stevemeier** [comment]
Please run the script with --verbose and attach the log to this issue.
With the information you have provided so far I can not help you.

**Comment by mithilasliit** [comment]
it return below lines 

DEBUG: Called as /var/errata_import/errata-import.pl --server localhost --errata errata.latest.xml --include-channels=centoschannel --rhsa-oval=/var/errata_import/com.redhat.rhsa-all.xml --publish --debug
DEBUG: Version is 20170930
404 Not Found

**Comment by stevemeier** [comment]
I have setup a clean Spacewalk 2.7 install on CentOS 7 and can not reproduce the issue.
Are you sure Spacewalk is running on localhost, port 80?
Have you logged in and created the initial organization and user?

**Comment by mithilasliit** [comment]
Yes I'm able to login to spacewalk interface using created user , it running on https it reject http traffic.

**Comment by stevemeier** [comment]
Sorry, I can't help you with that.

Please ask for advice on the Spacewalk mailing list: https://www.redhat.com/mailman/listinfo/spacewalk-list
