### ISSUE TITLE
What does the `os_release` signify, and how is it scraped?

### ISSUE THREAD

**Issue by hdavidzhu** [stevemeier/cefs#32]
Tangentially, would love to see some more documentation on each of these fields. Thank you!

**Comment by stevemeier** [comment]
`os_release` specifies the major release (7.x, 8.x) an errata applies to.

In CentOS 6 and 7 there was quite a bit of overlap but 7 and 8 are further apart so most errata apply to either 7 or 8.
One exception that comes to mind is the `tzdata` package, which is identical across major versions.

It can be scraped from the filename: el7 indicates an RPM is for major release 7, while el8 is used for major release 8.

**Comment by hdavidzhu** [comment]
Great, thank you!
