### ISSUE TITLE
No longer compatible with Uyuni 2021 04 following RPC changes.

### ISSUE THREAD

**Issue by digdilem** [stevemeier/cefs#33]
Not an issue with the script itself, but this no longer works with Uyuni - the forked Spacewalk replacement.

Uyuni changed api version to 25 last year, and --ignore-api-version allowed the script to continue working. 

However, as of the latest 2021 04 version of Uyuni, they have removed some API calls which now breaks the script.

Running the script returns this at the end and no errata is imported

`Fault returned from XML RPC Server, fault code 2609: redstone.xmlrpc.XmlRpcFault: A required patch attribute (advisory_status) was missing.`

Uyuni reference: https://www.uyuni-project.org/doc/2021.04/release-notes-uyuni-server.html#_removal_of_deprecated_xmlrpc_api_methods

**Comment by paususe** [comment]
@lucidd is this something we need to fix on the Uyuni side?

**Comment by stevemeier** [comment]
@digdilem Could you post more context from the debug log, please? Thanks

**Comment by digdilem** [comment]
Certainly - 

I ran with --debug and redirected to a file, attached. 

Output to stdio was:
```
DEBUG: Called as /usr/local/centos/errata-import.pl --server uyuni01 --errata /usr/local/centos/errata.latest.xml --publish --rhsa-oval /usr/local/centos/com.redhat.rhsa-RHEL7.xml --ignore-api-version --debug

Fault returned from XML RPC Server, fault code 2609: redstone.xmlrpc.XmlRpcFault: A required patch attribute (advisory_status) was missing.
```

[debug.txt](https://github.com/stevemeier/cefs/files/6399536/debug.txt)

**Comment by stevemeier** [comment]
Doing some quick digging, it seems that Uyuni has introduced a new mandatory field: `advisory_status`

Changes were commit here very recently -> https://github.com/uyuni-project/uyuni/commits/master/java/code/src/com/redhat/rhn/frontend/xmlrpc/errata/ErrataHandler.java

According to the source code documentation: `(Must be one of the following: "final", "stable", "testing", "retracted")`

However, I could find no API documentation that references this. Back in Spacewalk there were API docs for each release but I don't know how this is handled for Uyuni.

**Comment by paususe** [comment]
> Doing some quick digging, it seems that Uyuni has introduced a new mandatory field: `advisory_status`
> 
> Changes were commit here very recently -> [uyuni-project/uyuni@`master`/java/code/src/com/redhat/rhn/frontend/xmlrpc/errata/ErrataHandler.java (commits)](https://github.com/uyuni-project/uyuni/commits/master/java/code/src/com/redhat/rhn/frontend/xmlrpc/errata/ErrataHandler.java)
> 
> According to the source code documentation: `(Must be one of the following: "final", "stable", "testing", "retracted")`
> 
> However, I could find no API documentation that references this. Back in Spacewalk there were API docs for each release but I don't know how this is handled for Uyuni.

Ah, that's because of the support for retracted patches we have recently added. This is a SUSE-specific feature, we will talk about it tomorrow at Uyuni Community Hours:
https://github.com/uyuni-project/uyuni/wiki/Uyuni-Community-Hours

API docs here:
https://www.uyuni-project.org/uyuni-docs-api/uyuni/api/errata.html#apidoc-errata-create-1286968216

@hustodemon what should be the right value for CentOS errata? "final" or "stable"?

**Comment by stevemeier** [comment]
@paususe Shouldn't the API version number have been bumped up for this kind of change?

**Comment by paususe** [comment]
> @paususe Shouldn't the API version number have been bumped up for this kind of change?

Indeed. And we discussed it but I don't know why we did not bump it.

FYI: for CentOS, just use `final` as the `advisory_status`.

**Comment by stevemeier** [comment]
I haven't followed Uyuni development but from what little I know it seems that there is now a version `2021.02` and `2021.04` out there, both reporting API version `25`.

The first doesn't understand `advisory_status` and the later requires it. How are clients supposed to deal with that?

**Comment by paususe** [comment]
I'm afraid this time exception handling might be the only solution: try to insert one errata with advisory_status. If you get an error, try without.

**Comment by stevemeier** [comment]
What about using `api.systemVersion` to distinguish?
On my old box this reports `2020.11`.

**Comment by paususe** [comment]
> What about using `api.systemVersion` to distinguish?
> On my old box this reports `2020.11`.

That might work. It should report 2021.04 for Uyuni 2021.04.

**Comment by stevemeier** [comment]
@digdilem Could you give the attached version a try? This should check for the Uyuni version and set `advisory_status` when required. Thanks!

[errata-import.pl.txt](https://github.com/stevemeier/cefs/files/6408205/errata-import.pl.txt)

**Comment by digdilem** [comment]
@stevemeier
I'm pleased to confirm that this works perfectly and your changes seem to have resolved this issue. 

Thank you very much for your prompt attention in sorting this. 

Attached is the output from the run. No errors reported and returned a clean exit.

[centos-import.-nondebug-20210501SA.txt](https://github.com/stevemeier/cefs/files/6409046/centos-import.-nondebug-20210501SA.txt)

(Unrelated and possibly transient error - am getting a 404 on http://cefs.steve-meier.de/errata.latest.xml this morning, but was able to run the tests with a previous copy)

**Comment by phibid** [comment]
I confirm, so far so good, worked for me too. 

Thanks !

**Comment by stevemeier** [comment]
@digdilem The 404 probably appeared while an updated XML file was being deployed. I have changed the process slightly to hopefully prevent that in the future.

**Comment by hustodemon** [comment]
Hello everyone! In the end this got handled as a bug in Uyuni (because of the breakage of backwards-compatibility) and has been fixen in this PR: https://github.com/uyuni-project/uyuni/pull/3750. Uyuni will default to `final` in case the `advisory_status` is not explicitly specified in the `createErrata` API call. The fix will be included in the next release.
