### ISSUE TITLE
Errata script fails with: Unable to recognise encoding of this document at ... EncodingDetect.pm line 100.

### ISSUE THREAD

**Issue by brhavel** [stevemeier/cefs#38]
--2021-12-20 11:32:28--  http://cefs.steve-meier.de/errata.latest.xml
Resolving cefs.steve-meier.de (cefs.steve-meier.de)... 13.32.21.36, 13.32.21.92, 13.32.21.71, ...
Connecting to cefs.steve-meier.de (cefs.steve-meier.de)|13.32.21.36|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cefs.b-cdn.net/1fab63937ba4ddf4235ba2aad0934758f8e308d8/errata.latest.xml [following]
--2021-12-20 11:32:29--  https://cefs.b-cdn.net/1fab63937ba4ddf4235ba2aad0934758f8e308d8/errata.latest.xml
Resolving cefs.b-cdn.net (cefs.b-cdn.net)... 89.187.169.15
Connecting to cefs.b-cdn.net (cefs.b-cdn.net)|89.187.169.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1094464 (1.0M) [text/xml]
Saving to: ‘errata.latest.xml’

errata.latest.xml                                           100%[=========================================================================================================================================>]   1.04M  --.-KB/s    in 0.05s   

2021-12-20 11:32:29 (21.9 MB/s) - ‘errata.latest.xml’ saved [1094464/1094464]

--2021-12-20 11:32:29--  https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml
Resolving www.redhat.com (www.redhat.com)... 104.117.207.53, 2a02:26f0:1700:38a::d44, 2a02:26f0:1700:387::d44
Connecting to www.redhat.com (www.redhat.com)|104.117.207.53|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://access.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2 [following]
--2021-12-20 11:32:29--  https://access.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2
Resolving access.redhat.com (access.redhat.com)... 104.126.37.154, 104.126.37.128, 2a02:26f0:1700:11::b856:678d, ...
Connecting to access.redhat.com (access.redhat.com)|104.126.37.154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 940798 (919K) [application/x-bzip2]
Saving to: ‘com.redhat.rhsa-RHEL7.xml’

com.redhat.rhsa-RHEL7.xml                                   100%[=========================================================================================================================================>] 918.75K  --.-KB/s    in 0.05s   

2021-12-20 11:32:29 (19.5 MB/s) - ‘com.redhat.rhsa-RHEL7.xml’ saved [940798/940798]

--2021-12-20 11:32:29--  http://cefs.steve-meier.de/errata-import.tar
Resolving cefs.steve-meier.de (cefs.steve-meier.de)... 13.32.21.36, 13.32.21.92, 13.32.21.71, ...
Connecting to cefs.steve-meier.de (cefs.steve-meier.de)|13.32.21.36|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

errata-import.pl
INFO: Server is running API version 25
INFO: Server is running SYSTEM version 4.2.4
INFO: API version 25 is supported
INFO: Authentication successful
INFO: User has administrator access to this server
INFO: Loading errata XML
INFO: Loading Red Hat OVAL XML
Unable to recognise encoding of this document at /usr/lib/perl5/vendor_perl/5.26.1/XML/SAX/PurePerl/EncodingDetect.pm line 100.
Document requires an element [Ln: 1, Col: 0]
XML::Simple called at /usr/local/centos/errata-import.pl line 333.

**Comment by stevemeier** [comment]
Hello @brhavel,

please see the **News** section on the website:

> 2021-10-27: It seems that Red Hat is no longer serving their OVAL data as uncompressed XML and redirect to the bzip2-compressed version instead. You will need to adapt your download script to deal with that as Perl can not read bzip2 without creating new dependencies.

**Comment by stevemeier** [comment]
I have added some code in commit https://github.com/stevemeier/cefs/commit/f144faeb6103e7e4d0a1efd79c24de4c59bca900 to provide a better error message.
