### ISSUE TITLE
Uyuni 2022.03 - API version 26

### ISSUE THREAD

**Issue by Fredouye** [stevemeier/cefs#39]
Hi Steve

Uyuni 2022.03 is out, and brings API version 26 : https://www.uyuni-project.org/doc/2022.03/release-notes-uyuni-server.html#_new_xml_rpc_api_version_26

> Uyuni 2022.03 updates the XML-RPC API version from 25 to 26, in preparation for SUSE Manager 4.3
> There are no breaking changes to any methods.
> If any of your scripts are checking for the version 25, you can change them to use version 26 without any further changes.

I've tested this simple modification to errata-import.pl, it seems to work :

```perl
my @supportedapi = ( '10.9','10.11','11.00','11.1','12','13','13.0','14','14.0','15','15.0','16','16.0','17','17.0','18','18.0','19','19.0',
                     '20','20.0','21','21.0','22','22.0','23','23.0','24','25','26');
```

Result :

```bash
INFO: Server is running API version 26
INFO: Server is running SYSTEM version 2022.03
INFO: API version 26 is supported
```

Regards,

Frédéric

**Comment by stevemeier** [comment]
Hello @Fredouye,

thanks for testing. I have updated the script accordingly and the website should update soon (CDN).
