### ISSUE TITLE
Fault 2603: You are trying to publish an errata but have not selected any channels to publish to

### ISSUE THREAD

**Issue by Sebster7** [stevemeier/cefs#8]
I got a timeout error after the script (Sept version) had added and published many errata, so I upgraded to the latest and greatest version and then I got the following error:

INFO: Errata for CESA-2014:1359 already exists
INFO: Adding packages to CESA-2014:1359
INFO: Republishing CESA-2014:1359
Fault returned from XML RPC Server, fault code 2603: redstone.xmlrpc.XmlRpcFault: You are trying to publish an errata but have not selected any channels to publish to.  Errata must be published to at least one channel.

So I deleted CESA-2014:1359 from Spacewalk, ran the script again and got:

INFO: Adding packages to CESA-2016:2579
INFO: Republishing CESA-2016:2579
Fault returned from XML RPC Server, fault code 2603: redstone.xmlrpc.XmlRpcFault: You are trying to publish an errata but have not selected any channels to publish to.  Errata must be published to at least one channel.

I could obviously delete this one too, but it takes so long to reach this point, and I don't know how many times it is going to fail on similar errata.

I think the fix should come in 2 pieces:
(a) fix for the above issue;
(b) continuing on with the remaining errata to process in the event of this of this kind of non-fatal error, with an error count or summary at the bottom of the output to let you know there was a problem further up.

Cheers.

**Comment by stevemeier** [comment]
Please run the errata-import.pl script with --debug and attach the resulting output here.
Without this, it would be very hard to debug this.

Timeout errors are usually caused by the server not fulfilling the hardware specifications.

**Comment by Sebster7** [comment]
OK, attaching the last 27 lines of the output...

[Spacewalk Errata fault code 2603 redstone.xmlrpc.XmlRpcFault.txt](https://github.com/stevemeier/cefs/files/2001364/Spacewalk.Errata.fault.code.2603.redstone.xmlrpc.XmlRpcFault.txt)

Our servers do fulfill the hardware specs, but the errata-import.pl script does take a very long time to run.

**Comment by stevemeier** [comment]
I have added a check to make sure that there actually are channels to republish to.
This has been commited, which is why GitHub closed this issue automatically.

Please test it and re-open this issue if you run into the same problem again. Thanks!

**Comment by Sebster7** [comment]
Thanks, this fixes the issue on my system:

INFO: Errata created: 106
INFO: Errata updated: 0

real    37m39.385s
user    9m32.204s
sys     0m13.656s
