### ISSUE TITLE
CEFS Errata issue date in the future

### ISSUE THREAD

**Issue by gwgrant** [stevemeier/cefs#9]
I'm having a bit of trouble with errata 

CEBA-2018--0760,
CEBA-2018--0977, 
and CEBA-2018--0684.

The issue date in (up-to-date) CEFS xml file is 2018-08-26, yet it was released by Red Hat and lists.centos.org in April 2018.

Here's the text from the XML file for the 1st erratum:

```
<CEBA-2018--0760 description="Not available" from="centos-announce@centos.org" issue_date="2018-08-26 17:39:22" notes="Not available" product="CentOS Linux" references="https://access.redhat.com/errata/RHBA-2018:0760 https://lists.centos.org/pipermail/centos-cr-announce/2018-April/004734.html" release="1" solution="Not available" synopsis="CentOS audit BugFix Update" topic="Not available" type="Bug Fix Advisory">
    <os_arch>x86_64</os_arch>
    <os_arch>i686</os_arch>
    <os_release>7</os_release>
    <packages>audispd-plugins-2.8.1-3.el7.x86_64.rpm</packages>
    <packages>audit-2.8.1-3.el7.x86_64.rpm</packages>
    <packages>audit-libs-2.8.1-3.el7.i686.rpm</packages>
    <packages>audit-libs-2.8.1-3.el7.x86_64.rpm</packages>
    <packages>audit-libs-devel-2.8.1-3.el7.i686.rpm</packages>
    <packages>audit-libs-devel-2.8.1-3.el7.x86_64.rpm</packages>
    <packages>audit-libs-python-2.8.1-3.el7.x86_64.rpm</packages>
    <packages>audit-libs-static-2.8.1-3.el7.i686.rpm</packages>
    <packages>audit-libs-static-2.8.1-3.el7.x86_64.rpm</packages>
  </CEBA-2018--0760>
```

As this date is wrong and in the future it means it's not getting pulled into Spacewalk cloned channels, etc.

**Comment by stevemeier** [comment]
I have found the issue in the date parser which seems to have affected a total of 34.
In each case the month was wrong while other data (day, year, time) was correct.

An updated errata XML will be released tomorrow which will include the corrections.

Here is a list of the affected errata for reference:
CEBA-2013--1445
CEBA-2013--1742
CEBA-2015--0005
CEBA-2015--0007
CEBA-2015--0073
CEBA-2015--0081
CEBA-2015--0082
CEBA-2015--0123
CEBA-2015--0162
CEBA-2015--0399
CEBA-2015--0479
CEBA-2015--0512
CEBA-2015--1256
CEBA-2015--1278
CEBA-2015--1370
CEBA-2016--0744
CEBA-2016--0773
CEBA-2016--0883
**CEBA-2018--0684
CEBA-2018--0760
CEBA-2018--0977**
CEEA-2013--1516
CEEA-2014--0031
CEEA-2015--0122
CESA-2013--0663
CESA-2013--0668
CESA-2013--1457
CESA-2014--0043
CESA-2014--0044
CESA-2014--0189
CESA-2015--0118
CESA-2015--0165
CESA-2015--X003

**Comment by stevemeier** [comment]
New data is now available and issue should be fixed.

https://github.com/stevemeier/cefs/commit/09c34f4b30f1d0c57b681c064ce82ff39ad26f5b
